import json
import os

# 노트북 내용 정의 (JSON 구조)
notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# AI-Based Hybrid Text Analysis: Topic Modeling & Network Analysis\n",
    "## BERTopic, SNA, and LLM Prompting (Azure OpenAI)\n",
    "\n",
    "이 노트북은 연구 보고서에서 제안한 **'AI 기반 하이브리드 텍스트 분석 프레임워크'**를 구현합니다.\n",
    "\n",
    "**분석 프로세스:**\n",
    "1. **Data Loading & Preprocessing:** 뉴스 데이터 로드 및 전처리\n",
    "2. **BERTopic Analysis:** 동적 토픽 모델링을 통한 주요 이슈 및 시계열 변화 추적\n",
    "3. **Semantic Network Analysis (SNA):** 키워드 동시 출현 네트워크 시각화 (기술 생태계 지도)\n",
    "4. **LLM Prompt Generation:** 분석 결과를 바탕으로 심층 해석을 위한 LLM 프롬프트 자동 생성\n",
    "5. **LLM Integration (Azure):** Azure OpenAI를 연동하여 실제 분석 리포트 자동 생성"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import networkx as nx\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import re\n",
    "import os\n",
    "from collections import Counter\n",
    "from itertools import combinations\n",
    "from bertopic import BERTopic\n",
    "from sklearn.feature_extraction.text import CountVectorizer\n",
    "\n",
    "# Azure OpenAI 및 환경변수 로드\n",
    "from openai import AzureOpenAI\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "# 시각화 설정\n",
    "sns.set(style=\"whitegrid\")\n",
    "plt.rcParams['font.family'] = 'sans-serif' \n",
    "plt.rcParams['axes.unicode_minus'] = False\n",
    "\n",
    "# 데이터 경로\n",
    "DATA_DIR = \"../data/raw\"\n",
    "PROCESSED_DIR = \"../data/processed\"\n",
    "os.makedirs(PROCESSED_DIR, exist_ok=True)\n",
    "\n",
    "# .env 파일 로드 (프로젝트 루트 경로 기준)\n",
    "load_dotenv(dotenv_path=\"../.env\")\n",
    "\n",
    "print(\"Libraries Loaded & Environment Variables Checked.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Data Loading & Preprocessing\n",
    "def load_and_preprocess():\n",
    "    try:\n",
    "        sam_df = pd.read_csv(os.path.join(DATA_DIR, \"samsung_news.csv\"))\n",
    "        sk_df = pd.read_csv(os.path.join(DATA_DIR, \"skhynix_news.csv\"))\n",
    "    except FileNotFoundError:\n",
    "        print(\"데이터 파일이 없습니다. 더미 데이터를 생성합니다.\")\n",
    "        sam_df = pd.DataFrame({'date': ['2024-01-01'], 'title': ['삼성전자 GAA 파운드리'], 'content': ['삼성전자가 3나노 GAA 공정 양산을 시작했다.']})\n",
    "        sk_df = pd.DataFrame({'date': ['2024-01-01'], 'title': ['SK하이닉스 HBM3E'], 'content': ['SK하이닉스가 HBM3E를 엔비디아에 독점 공급한다.']})\n",
    "    \n",
    "    sam_df['company'] = 'Samsung'\n",
    "    sk_df['company'] = 'SKHynix'\n",
    "    df = pd.concat([sam_df, sk_df], ignore_index=True)\n",
    "    df['text'] = df['title'].fillna('') + \" \" + df['content'].fillna('')\n",
    "    df['date'] = pd.to_datetime(df['date'], format='mixed', errors='coerce')\n",
    "    df = df.dropna(subset=['date']).sort_values('date')\n",
    "    \n",
    "    def clean_text(text):\n",
    "        text = str(text)\n",
    "        text = re.sub(r'<[^>]+>', '', text)\n",
    "        text = re.sub(r'\\s+', ' ', text).strip()\n",
    "        return text\n",
    "    df['processed_text'] = df['text'].apply(clean_text)\n",
    "    return df\n",
    "\n",
    "df = load_and_preprocess()\n",
    "print(f\"Total Data: {len(df)} records\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 2. BERTopic Analysis\n",
    "def run_bertopic(docs, min_topic_size=30):\n",
    "    print(\"Initializing BERTopic...\")\n",
    "    korean_stopwords = ['기자', '배포', '금지', '무단', '전재', '위해', '통해', '관련', '대한', '이번', '있다', '했다', '밝혔다']\n",
    "    vectorizer_model = CountVectorizer(stop_words=korean_stopwords)\n",
    "\n",
    "    topic_model = BERTopic(\n",
    "        embedding_model=\"paraphrase-multilingual-MiniLM-L12-v2\",\n",
    "        vectorizer_model=vectorizer_model,\n",
    "        min_topic_size=min_topic_size,\n",
    "        verbose=True\n",
    "    )\n",
    "    topics, probs = topic_model.fit_transform(docs)\n",
    "    return topic_model, topics\n",
    "\n",
    "sample_df = df.tail(1000).copy()\n",
    "docs = sample_df['processed_text'].tolist()\n",
    "\n",
    "try:\n",
    "    topic_model, topics = run_bertopic(docs)\n",
    "    print(\"BERTopic Training Complete.\")\n",
    "    freq = topic_model.get_topic_info(); \n",
    "    print(freq.head(5))\n",
    "except Exception as e:\n",
    "    print(f\"BERTopic Error: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 3. Semantic Network Analysis (SNA)\n",
    "def extract_keywords_regex(text):\n",
    "    if not isinstance(text, str): return []\n",
    "    tech_terms = re.findall(r'\\b[A-Za-z][A-Za-z0-9]+\\b', text)\n",
    "    korean_nouns = re.findall(r'[가-힣]{2,}', text)\n",
    "    target_keywords = set(['HBM', 'DDR', 'NAND', 'AI', '반도체', '파운드리', '수율', '투자', '양산', \n",
    "                          '엔비디아', 'TSMC', 'GAA', '이익', '적자', 'CXL', 'PIM', 'SK하이닉스', '삼성전자'])\n",
    "    found = []\n",
    "    for word in tech_terms + korean_nouns:\n",
    "        w_upper = word.upper()\n",
    "        for target in target_keywords:\n",
    "            if target in w_upper or w_upper in target:\n",
    "                found.append(target)\n",
    "                break\n",
    "    return list(set(found))\n",
    "\n",
    "def draw_semantic_network(df, company_name, threshold=5):\n",
    "    subset = df[df['company'] == company_name].copy()\n",
    "    subset['keywords'] = subset['processed_text'].apply(extract_keywords_regex)\n",
    "    edge_list = []\n",
    "    for keywords in subset['keywords']:\n",
    "        if len(keywords) > 1:\n",
    "            edge_list.extend(combinations(sorted(keywords), 2))\n",
    "    edge_counts = Counter(edge_list)\n",
    "    G = nx.Graph()\n",
    "    for (u, v), count in edge_counts.items():\n",
    "        if count >= threshold: G.add_edge(u, v, weight=count)\n",
    "    return G\n",
    "\n",
    "G_sk = draw_semantic_network(sample_df, \"SKHynix\", threshold=20)\n",
    "G_sam = draw_semantic_network(sample_df, \"Samsung\", threshold=20)\n",
    "print(\"Networks Built.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 4. LLM Prompt Generation\n",
    "def generate_llm_prompt(G, company_name):\n",
    "    degree_dict = dict(G.degree(weight='weight'))\n",
    "    top_nodes = sorted(degree_dict.items(), key=lambda x: x[1], reverse=True)[:5]\n",
    "    top_keywords = [k[0] for k in top_nodes]\n",
    "    \n",
    "    prompt = f\"\"\"\n",
    "    [역할]\n",
    "    당신은 반도체 산업 전문 애널리스트입니다. 아래의 데이터 분석 결과를 바탕으로 통찰력 있는 보고서를 작성해 주세요.\n",
    "    \n",
    "    [분석 데이터: {company_name}]\n",
    "    1. 핵심 연결 키워드 (Top 5): {top_keywords}\n",
    "    2. 네트워크 특징: '{top_keywords[0]}' 키워드가 중심 허브 역할을 하며 기술 생태계를 주도함.\n",
    "    \n",
    "    [요청 사항]\n",
    "    1. **전략 진단:** 현재 {company_name}의 기술 전략이 '집중형'인지 '분산형'인지 진단해 주세요.\n",
    "    2. **성과 예측:** 특히 '{top_keywords[0]}' 기술이 AI 산업 트렌드와 결합하여 향후 어떤 재무적 성과를 낼지 추론해 주세요.\n",
    "    3. **약한 신호(Weak Signal):** 네트워크 주변부에 위치했을 가능성이 있는 차세대 기술을 제안하고 그 이유를 설명해 주세요.\n",
    "    \"\"\"\n",
    "    return prompt\n",
    "\n",
    "target_prompt = generate_llm_prompt(G_sk, \"SK하이닉스\")\n",
    "print(target_prompt)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 5. Azure OpenAI Integration\n",
    "\n",
    "# 환경 변수 확인 (디버깅용, 실제 키 값은 출력하지 않음)\n",
    "print(\"Azure OpenAI Config Check:\")\n",
    "print(f\"- Endpoint: {os.getenv('AZURE_OPENAI_ENDPOINT')}\")\n",
    "print(f\"- Deployment Name: {os.getenv('AZURE_OPENAI_DEPLOYMENT_NAME')}\")\n",
    "print(f\"- API Version: {os.getenv('AZURE_OPENAI_API_VERSION')}\")\n",
    "\n",
    "def query_azure_llm(prompt):\n",
    "    # 클라이언트 초기화\n",
    "    client = AzureOpenAI(\n",
    "        azure_endpoint = os.getenv(\"AZURE_OPENAI_ENDPOINT\"), \n",
    "        api_key = os.getenv(\"AZURE_OPENAI_API_KEY\"),  \n",
    "        api_version = os.getenv(\"AZURE_OPENAI_API_VERSION\")\n",
    "    )\n",
    "    \n",
    "    deployment_name = os.getenv(\"AZURE_OPENAI_DEPLOYMENT_NAME\") # e.g., 'gpt-4o'\n",
    "    \n",
    "    try:\n",
    "        print(\"🤖 Azure LLM에게 분석 요청 중... (잠시만 기다려주세요)\")\n",
    "        response = client.chat.completions.create(\n",
    "            model=deployment_name,\n",
    "            messages=[\n",
    "                {\"role\": \"system\", \"content\": \"You are a helpful assistant skilled in semiconductor industry analysis.\"},\n",
    "                {\"role\": \"user\", \"content\": prompt}\n",
    "            ],\n",
    "            temperature=0.7\n",
    "        )\n",
    "        return response.choices[0].message.content\n",
    "    except Exception as e:\n",
    "        return f\"❌ Error calling Azure OpenAI: {e}\"\n",
    "\n",
    "# 실행 예시 (환경 변수가 올바르게 설정되어 있다면 실행됨)\n",
    "if os.getenv('AZURE_OPENAI_API_KEY'):\n",
    "    analysis_result = query_azure_llm(target_prompt)\n",
    "    \n",
    "    print(\"\\n\" + \"=\"*20 + \" Azure LLM 분석 리포트 \" + \"=\"*20 + \"\\n\")\n",
    "    print(analysis_result)\n",
    "else:\n",
    "    print(\"\\n⚠️ .env 파일에 AZURE_OPENAI_API_KEY가 설정되지 않았습니다.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

# 파일 생성
output_path = "/home/arkwith/SKKU/tech_forcast/notebooks/02_advanced_analysis.ipynb"
os.makedirs(os.path.dirname(output_path), exist_ok=True)

with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(notebook_content, f, indent=1, ensure_ascii=False)

print(f"Notebook updated at {output_path}")
